import type { Product } from '@/types/product';

/**
 * Mock product data. Keep in service layer only;
 * components fetch via getProducts / getProductById.
 */
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Classic Cotton Tee',
    brand: 'BasicWear',
    category: 'T-Shirts',
    price: 29.99,
    originalPrice: 39.99,
    images: [
      'https://placehold.co/600x800/1a1a1a/fff?text=Tee+1',
      'https://placehold.co/600x800/2a2a2a/fff?text=Tee+2',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    isNew: true,
    inStock: true,
    rating: 4.5,
    reviewCount: 128,
  },
  {
    id: '2',
    name: 'Slim Fit Chinos',
    brand: 'UrbanStyle',
    category: 'Pants',
    price: 59.99,
    images: ['https://placehold.co/600x800/2a2a2a/fff?text=Chinos'],
    sizes: ['30', '32', '34', '36'],
    isNew: false,
    inStock: true,
    rating: 4.2,
    reviewCount: 84,
  },
  {
    id: '3',
    name: 'Oversized Hoodie',
    brand: 'ComfortCo',
    category: 'Hoodies',
    price: 79.99,
    originalPrice: 99.99,
    images: [
      'https://placehold.co/600x800/3a3a3a/fff?text=Hoodie',
      'https://placehold.co/600x800/4a4a4a/fff?text=Hoodie+2',
      'https://placehold.co/600x800/5a5a5a/fff?text=Hoodie+3',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    isNew: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 256,
  },
  {
    id: '4',
    name: 'Denim Jacket',
    brand: 'BasicWear',
    category: 'Jackets',
    price: 129.99,
    images: ['https://placehold.co/600x800/4a4a4a/fff?text=Jacket'],
    sizes: ['S', 'M', 'L', 'XL'],
    isNew: false,
    inStock: false,
    rating: 4.6,
    reviewCount: 42,
  },
  {
    id: '5',
    name: 'Running Shorts',
    brand: 'ActiveLife',
    category: 'Shorts',
    price: 34.99,
    images: ['https://placehold.co/600x800/5a5a5a/fff?text=Shorts'],
    sizes: ['S', 'M', 'L'],
    isNew: true,
    inStock: true,
    rating: 4.0,
    reviewCount: 67,
  },
];
